title: Fluid Flows
lang: en
description: CEE 348
remote_theme: clearpathrobotics/jekyll-rtd-theme

url: "https://mountain-hydrology-research-group.github.io"
baseurl: "/Fluid_Flows"

addons_branch: true
edit: true
copyright:
  revision: true
addons:
  - github
  - i18n
  - plugins
  - analytics

readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
