title: Fluid Flows
lang: en
description: CEE 348

remote_theme: rundocs/jekyll-rtd-theme@2.0.10

addons_branch: true
edit: true

copyright:
  revision: true

addons:
  - github
  - i18n
  - plugins
  - analytics

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

# optional plugins
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  
