title: Fluid Flows
lang: en
description: CEE 348
remote_theme: just-the-docs/just-the-docs

color_scheme: light
search_enabled: true
heading_anchors: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
